version: "3.9"
services:
  web:
    build: .
    ports:
      - "3010:3010"
    volumes:
      - ../compose-test:/db
    environment:
      DART_SCHEDULER_ENV: development
      DART_SCHEDULER_HOST: 0.0.0.0
      DART_SCHEDULER_PORT: 3010
      DART_SCHEDULER_AES_CIPHER: 2,3,2,1,3,77,2,3,31,2,65,111,35,111,1,2,3,9,2,64,111,7,111,1,2,3,211,2,34,111,33,111
      DART_SCHEDULER_DB_PATH: /db