name: scheduler
description: A simple lucifer application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  cron: ^0.5.1
  hive: ^2.2.3
  lucifer: ^1.0.7

dev_dependencies:
  lints: ^1.0.0
  test: 1.21.4
